### ISSUE TITLE
Proxy Configuration is broken in v8

### ISSUE THREAD

**Issue by jonask94** [auth0/auth0-deploy-cli#1004]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are using the auth0-deploy-cli in our CI/CD-process.
The automated import to our staging tenants is executed behind a proxy.
Therefore we have to use the `--proxy_url` configuration, which worked fine in the past.
We just updated the deploy-cli to the newest major-version v8.
With v8 the proxy configuration seems to be broken.
The deploy-cli is not able to authenticate or to do any requests: `FetchError: The request failed and the interceptors did not return an alternative response`
(Without the proxy-configuration the import works as expected)
As far as I understood from the changelogs and migration guides, this behaviour could be caused by migrating to `node-auth0/v4`.
At least I found a change regarding the proxy configuration here: https://github.com/auth0/node-auth0/blob/master/v4_MIGRATION_GUIDE.md#authentication-api

### Expectation

auth0-deploy-cli should be able to work with `--proxy_url` configuration in v8

### Reproduction

1. run the deploy-cli with `--proxy_url=http://sample.proxy:port`

### Deploy CLI version

8.4.1

### Node version

20.18.0

**Comment by jonask94** [comment]
Hi @kushalshit27 ,

Unfortunately I'm still getting the same error with v8.4.3:

`2025-01-09T08:06:38.168Z - error: The request failed and the interceptors did not return an alternative response`

**Comment by jonask94** [comment]
Hi @kushalshit27 
Sorry for answering late.

With the `--debug` option enabled, I get the following stack trace:

```
2025-01-20T08:17:48.030Z - debug: Start command export
2025-01-20T08:17:48.035Z - info: Creating debug_v8_4_3
2025-01-20T08:17:48.037Z - warn: Usage of the AUTH0_EXCLUDED_CLIENTS exclusion param is deprecated and may be removed from future major versions. See: https://github.com/auth0/auth0-deploy-cli/issues/451#user-content-deprecated-exclusion-props for details.
2025-01-20T08:17:48.618Z - error: Problem running command export
2025-01-20T08:17:48.618Z - error: The request failed and the interceptors did not return an alternative response
2025-01-20T08:17:48.618Z - debug: FetchError: The request failed and the interceptors did not return an alternative response
    at BaseAPI.fetch (/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0/dist/cjs/lib/runtime.js:84:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuth.request (/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0/dist/cjs/lib/runtime.js:115:26)
    at async grant (/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0/dist/cjs/auth/base-auth-api.js:86:22)
```

**Comment by jonask94** [comment]
Hi @kushalshit27,

thanks for the update. It seems to work with v8.5.0 👍
