### ISSUE TITLE
deploy complains about a resource guardian "webauthn-roaming" generated by dump

### ISSUE THREAD

**Issue by jondarrer** [auth0/auth0-deploy-cli#313]
### Description

> When dumping a tenant's config from Auth0 using `dump`, it creates a guardian resource **webauthn-roaming** that it doesn't recognise when deploying that config back into Auth0 using `deploy`.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

config: {
  AUTH0_EXPORT_IDENTIFIERS: false,
  AUTH0_ALLOW_DELETE: true,
  AUTH0_API_MAX_RETRIES: 10,
  AUTH0_DOMAIN: 'yyy.auth0.com',
  AUTH0_CLIENT_SECRET: secrets['the-secret'],
  AUTH0_CLIENT_ID: 'xxx',
}

DUMP:

➜  whodis git:(main) ✗ yarn workspace @proj/auth0-config dump-from-auth0
yarn workspace v1.22.10
yarn run v1.22.10
$ node dump-from-auth0.js
2021-01-29T15:06:40.123Z - info: Loading Auth0 Tenant Data
2021-01-29T15:06:40.124Z - info: Retrieving rules data from Auth0
2021-01-29T15:06:40.292Z - info: Retrieving rulesConfigs data from Auth0
2021-01-29T15:06:40.479Z - info: Retrieving hooks data from Auth0
2021-01-29T15:06:40.661Z - info: Retrieving pages data from Auth0
2021-01-29T15:06:41.087Z - info: Retrieving resourceServers data from Auth0
2021-01-29T15:06:41.289Z - info: Retrieving clients data from Auth0
2021-01-29T15:06:41.511Z - info: Retrieving databases data from Auth0
2021-01-29T15:06:41.734Z - info: Retrieving connections data from Auth0
2021-01-29T15:06:41.940Z - info: Retrieving tenant data from Auth0
2021-01-29T15:06:42.090Z - info: Retrieving emailProvider data from Auth0
2021-01-29T15:06:42.223Z - info: Retrieving emailTemplates data from Auth0
2021-01-29T15:06:47.271Z - info: Retrieving clientGrants data from Auth0
2021-01-29T15:06:47.424Z - info: Retrieving guardianFactors data from Auth0
2021-01-29T15:06:47.567Z - info: Retrieving guardianFactorProviders data from Auth0
2021-01-29T15:06:47.747Z - info: Retrieving guardianFactorTemplates data from Auth0
2021-01-29T15:06:47.941Z - info: Retrieving guardianPolicies data from Auth0
2021-01-29T15:06:49.800Z - info: Retrieving guardianPhoneFactorSelectedProvider data from Auth0
2021-01-29T15:06:50.344Z - info: Retrieving guardianPhoneFactorMessageTypes data from Auth0
2021-01-29T15:06:50.525Z - info: Retrieving roles data from Auth0
2021-01-29T15:06:50.648Z - info: Retrieving branding data from Auth0
2021-01-29T15:06:50.808Z - info: Retrieving prompts data from Auth0
2021-01-29T15:06:50.937Z - info: Retrieving migrations data from Auth0
2021-01-29T15:06:52.251Z - info: Writing tenant-config/pages/login.html
2021-01-29T15:06:52.252Z - info: Writing tenant-config/pages/login.json
2021-01-29T15:06:52.255Z - info: Writing tenant-config/database-connections/account/change_password.js
2021-01-29T15:06:52.256Z - info: Writing tenant-config/database-connections/account/create.js
2021-01-29T15:06:52.256Z - info: Writing tenant-config/database-connections/account/delete.js
2021-01-29T15:06:52.256Z - info: Writing tenant-config/database-connections/account/get_user.js
2021-01-29T15:06:52.257Z - info: Writing tenant-config/database-connections/account/login.js
2021-01-29T15:06:52.257Z - info: Writing tenant-config/database-connections/account/verify.js
2021-01-29T15:06:52.257Z - info: Writing tenant-config/database-connections/account/database.json
2021-01-29T15:06:52.258Z - info: Writing tenant-config/database-connections/Username-Password-Authentication/database.json
2021-01-29T15:06:52.259Z - info: Writing tenant-config/clients/auth0-deploy-cli-extension.json
2021-01-29T15:06:52.263Z - info: Writing tenant-config/connections/facebook.json
2021-01-29T15:06:52.264Z - info: Writing tenant-config/connections/google-oauth2.json
2021-01-29T15:06:52.264Z - info: Writing tenant-config/tenant.json
2021-01-29T15:06:52.265Z - info: Writing tenant-config/emails/provider.json
2021-01-29T15:06:52.265Z - info: Writing tenant-config/emails/verify_email.html
2021-01-29T15:06:52.265Z - info: Writing tenant-config/emails/verify_email.json
2021-01-29T15:06:52.266Z - info: Writing tenant-config/emails/welcome_email.html
2021-01-29T15:06:52.266Z - info: Writing tenant-config/emails/welcome_email.json
2021-01-29T15:06:52.266Z - info: Writing tenant-config/guardian/factors/sms.json
2021-01-29T15:06:52.266Z - info: Writing tenant-config/guardian/factors/push-notification.json
2021-01-29T15:06:52.267Z - info: Writing tenant-config/guardian/factors/otp.json
2021-01-29T15:06:52.267Z - info: Writing tenant-config/guardian/factors/email.json
2021-01-29T15:06:52.267Z - info: Writing tenant-config/guardian/factors/duo.json
2021-01-29T15:06:52.267Z - info: Writing tenant-config/guardian/factors/webauthn-roaming.json
2021-01-29T15:06:52.268Z - info: Writing tenant-config/guardian/phoneFactorMessageTypes.json
2021-01-29T15:06:52.268Z - info: Writing tenant-config/guardian/phoneFactorSelectedProvider.json
2021-01-29T15:06:52.268Z - info: Writing tenant-config/guardian/policies.json
2021-01-29T15:06:52.269Z - info: Export Successful
✨  Done in 13.11s.
✨  Done in 13.24s.

DEPLOY:

➜  proj git:(main) ✗ yarn workspace @proj/auth0-config deploy-into-auth0
yarn workspace v1.22.10
yarn run v1.22.10
$ node deploy-into-auth0.js
2021-01-29T15:07:41.292Z - info: Processing directory tenant-config
2021-01-29T15:07:41.296Z - warn: Skipping invalid database script file: tenant-config/database-connections/account/login.spec.js
2021-01-29T15:07:41.301Z - info: Getting access token for xxx/yyy.auth0.com
2021-01-29T15:07:41.351Z - error: uncaughtException: Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[5].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
] date=Fri Jan 29 2021 15:07:41 GMT+0000 (Greenwich Mean Time), pid=69985, uid=501, gid=20, cwd=/Users/me/Work/proj/packages/auth0-config, execPath=/opt/homebrew/Cellar/node/15.5.1/bin/node, version=v15.5.1, argv=[/opt/homebrew/Cellar/node/15.5.1/bin/node, /Users/me/Work/proj/packages/auth0-config/deploy-into-auth0.js], rss=93192192, heapTotal=60571648, heapUsed=38795304, external=2122851, arrayBuffers=1044518, loadavg=[1.7734375, 1.869140625, 1.95654296875], uptime=678883, trace=[column=13, file=/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/auth0/index.js, function=Auth0.validate, line=71, method=validate, native=false, column=15, file=/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/deploy.js, function=Object.deploy, line=24, method=deploy, native=false, column=52, file=/Users/me/Work/proj/node_modules/auth0-deploy-cli/lib/commands/import.js, function=deploy, line=72, method=null, native=false, column=5, file=node:internal/process/task_queues, function=processTicksAndRejections, line=93, method=null, native=false], stack=[Error: Schema validation failed loading [,     {,         "keyword": "enum",,         "dataPath": ".guardianFactors[5].name",,         "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",,         "params": {,             "allowedValues": [,                 "sms",,                 "push-notification",,                 "otp",,                 "email",,                 "duo",             ],         },,         "message": "should be equal to one of the allowed values",     }, ],     at Auth0.validate (/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/auth0/index.js:71:13),     at Object.deploy (/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/deploy.js:24:15),     at deploy (/Users/me/Work/proj/node_modules/auth0-deploy-cli/lib/commands/import.js:72:52),     at processTicksAndRejections (node:internal/process/task_queues:93:5)]
2021-01-29T15:07:41.351Z - error: uncaughtException: Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[5].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
] date=Fri Jan 29 2021 15:07:41 GMT+0000 (Greenwich Mean Time), pid=69985, uid=501, gid=20, cwd=/Users/me/Work/proj/packages/auth0-config, execPath=/opt/homebrew/Cellar/node/15.5.1/bin/node, version=v15.5.1, argv=[/opt/homebrew/Cellar/node/15.5.1/bin/node, /Users/me/Work/proj/packages/auth0-config/deploy-into-auth0.js], rss=93274112, heapTotal=60571648, heapUsed=38851424, external=2122915, arrayBuffers=1044542, loadavg=[1.7734375, 1.869140625, 1.95654296875], uptime=678883, trace=[column=13, file=/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/auth0/index.js, function=Auth0.validate, line=71, method=validate, native=false, column=15, file=/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/deploy.js, function=Object.deploy, line=24, method=deploy, native=false, column=52, file=/Users/me/Work/proj/node_modules/auth0-deploy-cli/lib/commands/import.js, function=deploy, line=72, method=null, native=false, column=5, file=node:internal/process/task_queues, function=processTicksAndRejections, line=93, method=null, native=false], stack=[Error: Schema validation failed loading [,     {,         "keyword": "enum",,         "dataPath": ".guardianFactors[5].name",,         "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",,         "params": {,             "allowedValues": [,                 "sms",,                 "push-notification",,                 "otp",,                 "email",,                 "duo",             ],         },,         "message": "should be equal to one of the allowed values",     }, ],     at Auth0.validate (/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/auth0/index.js:71:13),     at Object.deploy (/Users/me/Work/proj/node_modules/auth0-source-control-extension-tools/lib/deploy.js:24:15),     at deploy (/Users/me/Work/proj/node_modules/auth0-deploy-cli/lib/commands/import.js:72:52),     at processTicksAndRejections (node:internal/process/task_queues:93:5)]

NB. The clue in the error is ` dataPath: .guardianFactors[5].name` which was the **webauthn-roaming.json** file.

A temporary work-around is to remove this resource, and the deploy works. However, it re-appears on each subsequent dump (and each subsequent deploy needs it to be removed again.)

### Environment

> Please provide the following:

- **Version of this library used:** 5.5.0
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** node 15.5.1 on MacOS (M1/arm64) and node 14.15.4 on Ubuntu 20.04 Linux (x86_64), MacOS (i5/x86_64) and Windows 10
- **Other modules/plugins/libraries that might be involved:**

**Comment by jondarrer** [comment]
This appears to be fixed. Interestingly, there haven't been any changes to the tool since I posted this issue - and none of the changes in the month prior appear to have anything to do with the bug. So, perhaps it was a backend change which fixed it.
