### ISSUE TITLE
Hitting rate limits when pushing 100 new rules.

### ISSUE THREAD

**Issue by tomatualus** [auth0/auth0-deploy-cli#317]
### Description

Hello. 

I am testing this npm package, and seems like i am hitting rate limits, as the error below suggests.
First off it created approximately 20~ rules and then reported that the rate limit has been reached.
Then, when ran again after a few minutes, it listed 1 of the created rules in a warning log message and then errored on the rate limit again.

### Reproduction

1. Generate a lot of rules. I created a C# application, that generates 100 rules in the directory. (I can share the code)

Then using this config.json (secret domain etc removed obviously)
```json
{
    "AUTH0_ALLOW_DELETE": false
}
```
And running this deployment.js for the first time
```javascript
import { deploy } from 'auth0-deploy-cli';

deploy({
    input_file: "./", // Current directory holds all the ./rules etc directories
    config_file: "./config.json",
});
```

I get the following output

```
C:\miscprojs\testauth0\deployment>npm run deploy

> deployment@1.0.0 deploy C:\testauth0\deployment
> node deployment.js

2021-02-11T14:41:48.352Z - info: Processing directory ./
2021-02-11T14:41:48.578Z - info: Getting access token for ~removed~
2021-02-11T14:41:48.954Z - info: Created [rules]: {"name":"Rule-10","order":10}
2021-02-11T14:41:48.958Z - info: Created [rules]: {"name":"Rule-0","order":0}
2021-02-11T14:41:48.962Z - info: Created [rules]: {"name":"Rule-1","order":1}
2021-02-11T14:41:49.106Z - info: Created [rules]: {"name":"Rule-12","order":12}
2021-02-11T14:41:49.111Z - info: Created [rules]: {"name":"Rule-11","order":11}
2021-02-11T14:41:49.128Z - info: Created [rules]: {"name":"Rule-13","order":13}
2021-02-11T14:41:49.237Z - info: Created [rules]: {"name":"Rule-14","order":14}
2021-02-11T14:41:49.284Z - info: Created [rules]: {"name":"Rule-15","order":15}
2021-02-11T14:41:49.936Z - info: Created [rules]: {"name":"Rule-16","order":16}
2021-02-11T14:41:49.943Z - info: Created [rules]: {"name":"Rule-18","order":18}
2021-02-11T14:41:49.982Z - info: Created [rules]: {"name":"Rule-17","order":17}
2021-02-11T14:41:51.709Z - info: Created [rules]: {"name":"Rule-19","order":19}
2021-02-11T14:41:51.753Z - info: Created [rules]: {"name":"Rule-2","order":2}
2021-02-11T14:41:51.787Z - info: Created [rules]: {"name":"Rule-20","order":20}
2021-02-11T14:41:51.838Z - info: Created [rules]: {"name":"Rule-21","order":21}
2021-02-11T14:41:53.345Z - info: Created [rules]: {"name":"Rule-23","order":23}
2021-02-11T14:41:53.479Z - info: Created [rules]: {"name":"Rule-25","order":25}
2021-02-11T14:41:53.704Z - info: Created [rules]: {"name":"Rule-26","order":26}
2021-02-11T14:41:53.846Z - info: Created [rules]: {"name":"Rule-27","order":27}
(node:15012) UnhandledPromiseRejectionWarning: Error: Problem creating rules {"name":"Rule-28","order":28}
Forbidden: You reached the limit of entities of this type for this tenant.
    at C:\testauth0\deployment\node_modules\auth0-source-control-extension-tools\lib\auth0\handlers\default.js:169:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

And running it again after 2~ minutes results in this output.

```
C:\miscprojs\testauth0\deployment>npm run deploy

> deployment@1.0.0 deploy C:\testauth0\deployment
> node deployment.js

2021-02-11T14:43:05.472Z - info: Processing directory ../
2021-02-11T14:43:05.694Z - info: Getting access token for ~removed~
(node:21280) UnhandledPromiseRejectionWarning: Error: Problem creating rules {"name":"Rule-22","order":22}
Forbidden: You reached the limit of entities of this type for this tenant.
    at C:\testauth0\deployment\node_modules\auth0-source-control-extension-tools\lib\auth0\handlers\default.js:169:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

Seems like i have the same output as in the second time even after 30 minutes...

### Environment

- **Version of this library used:** "auth0-deploy-cli": "^5.5.0"

**Comment by tomatualus** [comment]
It seems like i can't read errors - i reached the maximum entity limit -_-. But how the hell did i created 20 rules, if free plan covers only 10 rules?

**Comment by shushen** [comment]
Yes, it appears you've hit entity limits, for more information on how entity limit works, please kindly refer to https://auth0.com/docs/policies/entity-limit-policy
