### ISSUE TITLE
Handle 429 Too Many Requests errors

### ISSUE THREAD

**Issue by willthames** [auth0/auth0-deploy-cli#33]
I would expect an auth0 client to understand a 429 response issued by the auth0 servers and back off gracefully.

```
2018-08-02T05:13:22.210Z - debug: Error: {"statusCode":429,"error":"Too Many Requests"}
2018-08-02T05:13:22.210Z - debug: StackTrace: APIError: {"statusCode":429,"error":"Too Many Requests"}
    at /tmp/node_modules/rest-facade/src/Client.js:295:21
    at Request.callback (/tmp/node_modules/superagent/lib/node/index.js:688:3)
    at /tmp/node_modules/superagent/lib/node/index.js:883:18
    at Stream.<anonymous> (/tmp/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:106:13)
    at Stream.emit (events.js:208:7)
    at Unzip.<anonymous> (/tmp/node_modules/superagent/lib/node/unzip.js:53:12)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2018-08-02T05:13:22.214Z - error: Exiting due to error: {"statusCode":429,"error":"Too Many Requests"}
2018-08-02T05:13:22.214Z - error: APIError: {"statusCode":429,"error":"Too Many Requests"}
    at /tmp/node_modules/rest-facade/src/Client.js:295:21
    at Request.callback (/tmp/node_modules/superagent/lib/node/index.js:688:3)
    at /tmp/node_modules/superagent/lib/node/index.js:883:18
    at Stream.<anonymous> (/tmp/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:106:13)
    at Stream.emit (events.js:208:7)
    at Unzip.<anonymous> (/tmp/node_modules/superagent/lib/node/unzip.js:53:12)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by fyockm** [comment]
@willthames could you please provide a little more context around what you are doing to hit the rate limit? specific steps to duplicate would be helpful.
there is [retry logic in place to handle a 429 response](https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/23), but perhaps it needs to be revisited.

**Comment by willthames** [comment]
@fyockm thanks for that - you reminded me that I should at least check whether I was running a recent version. I updated to latest, and the backoff logic does seem to work well.

I'll close this now, thanks again
