### ISSUE TITLE
APIError: read ECONNRESET on creating client

### ISSUE THREAD

**Issue by saurabhdevops** [auth0/auth0-deploy-cli#35]
Hi Team,

First of all awesome tool! Simply love it. Works like a charm!

The issue I am having is when I try to create clients. Note taht with the same config, I am able to create/update rules and in the same workflow I am getting error for creating clients.

The error Logs below:
```
2018-10-04T13:09:13.015Z - debug: Creating clients...
2018-10-04T13:09:13.017Z - debug: Creating clients grafana-dev: {"allowed_clients":[],"allowed_logout_urls":[],"allowed_origins":[],"app_type":"regular_web","callbacks":["https://grafana.horizondev.cloud/login/generic_oauth"],"cross_origin_auth":false,"custom_login_page_on":true,"description":"","grant_types":["authorization_code","implicit","refresh_token","client_credentials"],"jwt_configuration":{"alg":"RS256","lifetime_in_seconds":36000},"logo_uri":"","name":"grafana-dev","oidc_conformant":true,"sso":false,"sso_disabled":false,"token_endpoint_auth_method":"client_secret_post","web_origins":[]}
2018-10-04T13:09:13.599Z - debug: Error: read ECONNRESET
2018-10-04T13:09:13.602Z - debug: StackTrace: APIError: read ECONNRESET
    at C:\Users\z003rpaf\AppData\Roaming\npm\node_modules\auth0-deploy-cli\node_modules\rest-facade\src\Client.js:358:22
    at Request.callback (C:\Users\z003rpaf\AppData\Roaming\npm\node_modules\auth0-deploy-cli\node_modules\superagent\lib\node\index.js:728:3)
    at ClientRequest.req.once.err (C:\Users\z003rpaf\AppData\Roaming\npm\node_modules\auth0-deploy-cli\node_modules\superagent\lib\node\index.js:647:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2018-10-04T13:09:13.607Z - debug: Sending progress to Slack.
2018-10-04T13:09:13.610Z - error: Exiting due to error: "read ECONNRESET"
2018-10-04T13:09:13.612Z - error: APIError: read ECONNRESET
    at C:\Users\z003rpaf\AppData\Roaming\npm\node_modules\auth0-deploy-cli\node_modules\rest-facade\src\Client.js:358:22
    at Request.callback (C:\Users\z003rpaf\AppData\Roaming\npm\node_modules\auth0-deploy-cli\node_modules\superagent\lib\node\index.js:728:3)
    at ClientRequest.req.once.err (C:\Users\z003rpaf\AppData\Roaming\npm\node_modules\auth0-deploy-cli\node_modules\superagent\lib\node\index.js:647:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by stevezau** [comment]
Hi @saurabhdevops we have released a new version of auth0-deploy-cli which was a full rewrite.

Can you please try again with the new updated version? (see README for notes)

**Comment by fyockm** [comment]
Closing this issue because it is stale. Please reopen if your error was not fixed with Deploy CLI v2.
