### ISSUE TITLE
Latest 7.1.0 version fails with exception

### ISSUE THREAD

**Issue by ruslan-belinskyy** [auth0/auth0-deploy-cli#360]
7.0.0 version works fine

Exception log:
```
2021-06-23T22:10:19.524Z - debug: TypeError: Cannot read property 'filter' of undefined
    at ActionHandler.processChanges (/usr/local/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/actions.js:243:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Auth0.runStage (/usr/local/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/index.js:61:16)
    at async Auth0.processChanges (/usr/local/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/index.js:89:5)
    at async deploy (/usr/local/lib/node_modules/auth0-deploy-cli/lib/tools/deploy.js:25:3)
    at async deploy (/usr/local/lib/node_modules/auth0-deploy-cli/lib/commands/import.js:68:3)
    at async run (/usr/local/lib/node_modules/auth0-deploy-cli/lib/index.js:37:3)
```

**Comment by shushen** [comment]
Thanks for the report, should be fixed in https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.1.1 which has just been released.
