### ISSUE TITLE
Pages YAML handler type error, expecting buffer received undefined

### ISSUE THREAD

**Issue by dejwsz** [auth0/auth0-deploy-cli#365]
Tested on MacOS 11.4
Installed via: npm i -g auth0-deploy-cli

npm version
{
  npm: '7.19.1',
  node: '16.5.0',
  v8: '9.1.269.38-node.20',
  uv: '1.41.1',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

a0deploy export -d -c ./config.json -f yaml -o ./result

2021-07-15T19:19:18.339Z - debug: Start command export
2021-07-15T19:19:18.813Z - info: Loading Auth0 Tenant Data
2021-07-15T19:19:18.813Z - info: Retrieving rules data from Auth0
2021-07-15T19:19:19.031Z - info: Retrieving rulesConfigs data from Auth0
2021-07-15T19:19:19.234Z - info: Retrieving hooks data from Auth0
2021-07-15T19:19:19.414Z - info: Retrieving pages data from Auth0
2021-07-15T19:19:19.844Z - info: Retrieving resourceServers data from Auth0
2021-07-15T19:19:20.023Z - info: Retrieving clients data from Auth0
2021-07-15T19:19:20.215Z - info: Retrieving databases data from Auth0
2021-07-15T19:19:20.413Z - info: Retrieving connections data from Auth0
2021-07-15T19:19:20.606Z - info: Retrieving tenant data from Auth0
2021-07-15T19:19:20.821Z - info: Retrieving emailProvider data from Auth0
2021-07-15T19:19:21.079Z - info: Retrieving emailTemplates data from Auth0
2021-07-15T19:19:27.242Z - info: Retrieving clientGrants data from Auth0
2021-07-15T19:19:27.414Z - info: Retrieving guardianFactors data from Auth0
2021-07-15T19:19:27.586Z - info: Retrieving guardianFactorProviders data from Auth0
2021-07-15T19:19:27.775Z - info: Retrieving guardianFactorTemplates data from Auth0
2021-07-15T19:19:27.972Z - info: Retrieving guardianPolicies data from Auth0
2021-07-15T19:19:28.112Z - info: Retrieving guardianPhoneFactorSelectedProvider data from Auth0
2021-07-15T19:19:30.442Z - info: Retrieving guardianPhoneFactorMessageTypes data from Auth0
2021-07-15T19:19:30.644Z - info: Retrieving roles data from Auth0
2021-07-15T19:19:30.831Z - info: Retrieving branding data from Auth0
2021-07-15T19:19:30.979Z - info: Retrieving prompts data from Auth0
2021-07-15T19:19:31.135Z - info: Retrieving migrations data from Auth0
2021-07-15T19:19:31.321Z - info: Retrieving actions data from Auth0
2021-07-15T19:19:31.580Z - info: Retrieving triggers data from Auth0
2021-07-15T19:19:35.142Z - info: Retrieving organizations data from Auth0
2021-07-15T19:19:35.659Z - info: Writing mytest/rules/Add email to access token.js
2021-07-15T19:19:35.662Z - info: Writing mytest/pages/guardian_multifactor.html
2021-07-15T19:19:35.680Z - info: Exporting rules
2021-07-15T19:19:35.680Z - info: Exporting hooks
2021-07-15T19:19:35.680Z - info: Exporting rulesConfigs
2021-07-15T19:19:35.681Z - debug: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2136:5)
    at /usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/handlers/pages.js:47:25
    at Array.map (<anonymous>)
    at Object.dump (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/handlers/pages.js:38:19)
    at /usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:119:36
    at Array.map (<anonymous>)
    at exports.default.dump (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:117:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deploy (/usr/local/lib/node_modules/auth0-deploy-cli/lib/commands/export.js:76:3)
    at async run (/usr/local/lib/node_modules/auth0-deploy-cli/lib/index.js:39:3)
2021-07-15T19:19:35.681Z - info: Exporting databases
2021-07-15T19:19:35.681Z - info: Exporting clientGrants
2021-07-15T19:19:35.681Z - info: Exporting resourceServers
2021-07-15T19:19:35.681Z - info: Exporting clients
2021-07-15T19:19:35.682Z - info: Exporting connections
2021-07-15T19:19:35.682Z - info: Exporting tenant
2021-07-15T19:19:35.682Z - info: Exporting emailProvider
2021-07-15T19:19:35.682Z - info: Exporting emailTemplates
2021-07-15T19:19:35.682Z - info: Exporting guardianFactors
2021-07-15T19:19:35.682Z - info: Exporting guardianFactorProviders
2021-07-15T19:19:35.682Z - info: Exporting guardianFactorTemplates
2021-07-15T19:19:35.682Z - info: Exporting roles
2021-07-15T19:19:35.682Z - info: Exporting migrations
2021-07-15T19:19:35.682Z - info: Exporting guardianPhoneFactorMessageTypes
2021-07-15T19:19:35.682Z - info: Exporting guardianPhoneFactorSelectedProvider
2021-07-15T19:19:35.682Z - info: Exporting guardianPolicies
2021-07-15T19:19:35.682Z - info: Exporting actions
2021-07-15T19:19:35.682Z - info: Exporting organizations
2021-07-15T19:19:35.682Z - info: Exporting triggers
2021-07-15T19:19:35.683Z - error: Problem running command export
2021-07-15T19:19:35.683Z - error: Problem exporting pages
2021-07-15T19:19:35.683Z - debug: Error: Problem exporting pages
    at /usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:131:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 3)
    at async exports.default.dump (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:117:5)
    at async deploy (/usr/local/lib/node_modules/auth0-deploy-cli/lib/commands/export.js:76:3)
    at async run (/usr/local/lib/node_modules/auth0-deploy-cli/lib/index.js:39:3)

**Comment by jennygordon-nearmap** [comment]
I'm also experiencing this. This is also my first time using the tool. 

- I've eliminated permissions as an issue, as I used an Application Client which had all possible permissions. 
- I also tried `auth0-deploy-cli` version `7.2.1` as well as `7.3.1`. 
- My tenant in us.auth0.com barely has anything deployed.

**Comment by willvedd** [comment]
@richarddbarnett Looping back to this, can you re-summarize this issue? I'm having trouble identifying the true culprit here. Is this a case where the tool expects an HTML template but none is found?

**Comment by richarddbarnett** [comment]
@willvedd sorry, it's been so long I don't remember the detail.

**Comment by willvedd** [comment]
Hi folks, can anyone comment if this is still an open issue?  The `TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined` error points to the pages handler trying to write a file from an undefined value. Looking in the handler, I believe [this specific line](https://github.com/auth0/auth0-deploy-cli/blob/master/src/context/yaml/handlers/pages.ts#L45) is the culprit, it appears that it's trying to pull the `html` property when it may not be set. 

The question I have is why is this happening, and how can it be recreated to troubleshoot. I'd be happy to look into this but I'm unable to recreate at the moment.

**Comment by camfulton** [comment]
@willvedd I'm currently facing the problem in the opener of this issue, I believe.

```
2022-04-21T13:19:31.625Z - error: Problem running command export
2022-04-21T13:19:31.625Z - error: Problem exporting pages
2022-04-21T13:19:31.625Z - debug: Error: Problem exporting pages
    at YAMLContext.<anonymous> (/usr/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:124:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Let me know if there's anything I can provide to help clear it up.

**Comment by willvedd** [comment]
@camfulton Really appreciate the response. I believe the issue is when one of these page templates returns an `undefined` value from the Management API but I'm unsure of how that would ever happen. Even when empty, despite being enabled or disabled, the HTML value of the template will at the very least return an empty string. A simple solution here is a simple undefined check before attempting to write, but I'd like to better understand what particular use case this is solving for. So with that said, do you know why any of your templates (login, password reset, error page, MFA) would not have a valid string HTML value?

**Comment by camfulton** [comment]
@willvedd I can't think of any reason this would be the case. We are using whatever the legacy templating system is and (as far as I know) have only modified the login template at the moment. I tried setting that template to nothing but "<html></html>" and still encountered the error.

For what it's worth, that template is also successfully exported to my local filesystem before the error occurs. It is the only template in the pages directory in the export.

**Comment by willvedd** [comment]
Still don't know exactly why this occurs, but the fix is to just coerce the undefined HTML template into an empty string which provides more compatibility with the tool and should be of no consequences to any other configuration. Just added that in with [v7.14.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.14.0) so please update and give it a shot! If anyone continues to experience this issue, I'd be happy to reopen. Thanks for the patience!
