### ISSUE TITLE
Error deploying ruleconfig in directory mode

### ISSUE THREAD

**Issue by iamjoeker** [auth0/auth0-deploy-cli#479]
### Description

As of v7.7.0 released earlier today, attempting to deploy ruleconfig assets fails with an error. This issue was not present in 7.6.0. 

### Reproduction

1. Create a directory mode setup with ruleconfig assets defined
2. Deploy
3. Observe error:
  ```
  2022-04-06T17:55:25.326Z - debug: Start command deploy
  2022-04-06T17:55:25.655Z - info: Processing directory .
  2022-04-06T17:55:26.770Z - debug: Start processChanges for rulesConfigs [delete:0] [update:2], [create:0], [conflicts:0]
  2022-04-06T17:55:26.771Z - error: Problem running command deploy during stage processChanges when processing type rulesConfigs
  2022-04-06T17:55:26.772Z - error: Cannot read property 'bind' of undefined
  2022-04-06T17:55:26.772Z - debug: TypeError: Cannot read property 'bind' of undefined
      at RulesConfigsHandler.getClientFN (<redacted>/.config/yarn/global/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/default.js:45:31)
      at Proxy.generator (<redacted>/.config/yarn/global/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/default.js:200:43)
      at Proxy.generator (<redacted>/.config/yarn/global/node_modules/promise-pool-executor/public/pool.js:200:42)
      at Proxy._run (<redacted>/.config/yarn/global/node_modules/promise-pool-executor/private/task.js:212:39)
      at Proxy._triggerNow (<redacted>/.config/yarn/global/node_modules/promise-pool-executor/public/pool.js:267:22)
      at Proxy.addGenericTask (<redacted>/.config/yarn/global/node_modules/promise-pool-executor/public/pool.js:102:14)
      at Proxy.addEachTask (<redacted>/.config/yarn/global/node_modules/promise-pool-executor/public/pool.js:186:21)
      at RulesConfigsHandler.<anonymous> (<redacted>/.config/yarn/global/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/default.js:197:18)
      at Generator.next (<anonymous>)
      at fulfilled (<redacted>/.config/yarn/global/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/default.js:5:58)
```

### Environment

* auth0-deploy-cli: v7.7.0
* node: lts/fermium (v14.18.2)
* OS: macOS 12.3.1

**Comment by willvedd** [comment]
Hey thanks for reporting this. Would it be possible for you to provide a sample configuration file (with sensitive details redacted) to me to recreate on my end?

**Comment by iamjoeker** [comment]
@willvedd Sure. I'm hitting the error with the rules config which are just a key and value from an export. Here's an example. I tried with and without the keyword replacement. This same config works ok with v7.6.0.

```json
{
  "key": "SLACK_HOOK_URL",
  "value": "##SLACK_HOOK_URL##"
}
```

**Comment by joclegg** [comment]
Getting similar issues

**Comment by GrzegorzKozub** [comment]
Same problem for us since 7.7.0. Worked fine in 7.6.0.
