### ISSUE TITLE
v7.10.0 TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by charlesdarkwind** [auth0/auth0-deploy-cli#518]
### Description

When running command `a0deploy import --config_file tenant_config.json --input_file tenant.yaml --no-env --debug`, deploy fails with error. Reverting to 7.9.0 fixes the issue

```
[Container] 2022/04/28 13:43:07 Running command a0deploy import --config_file tenant_config.json --input_file tenant.yaml --no-env --debug
2022-04-28T13:43:08.256Z - debug: Start command import
2022-04-28T13:43:08.625Z - debug: Loading YAML from /codebuild/output/src363754723/src/auth0/tenant.yaml
2022-04-28T13:43:08.723Z - debug: TypeError: Cannot read property 'map' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/handlers/branding.js:41:43)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/handlers/branding.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/handlers/branding.js:4:12)
    at Object.parse (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/handlers/branding.js:30:12)
    at YAMLContext.<anonymous> (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:78:50)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:8:71
    at new Promise (<anonymous>)
2022-04-28T13:43:08.723Z - error: Problem running command import
2022-04-28T13:43:08.723Z - error: Problem deploying branding
2022-04-28T13:43:08.723Z - debug: Error: Problem deploying branding
    at YAMLContext.<anonymous> (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:85:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/auth0-deploy-cli/lib/context/yaml/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Reproduction

run command `a0deploy import --config_file tenant_config.json --input_file tenant.yaml --no-env --debug`

branding part of the template:

```
branding:
  colors:
    page_background: '#00416B'
    primary: '#00416B'
  logo_url: >-
    https://some_url.png
```

### Environment

- v7.10.0
- Linux
- 3 GB memory, 2 vCPUs
- nodejs: 14

**Comment by willvedd** [comment]
Tested with the above config and confirm that this has been fixed with the [7.11.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.11.0) release. Please give it a go!
