### ISSUE TITLE
Bad Request on pushing prompts/custom-text.json file

### ISSUE THREAD

**Issue by AliBazzi** [auth0/auth0-deploy-cli#539]
### Description

Unable to push prompts/custom-text.json with the version 7.12.1 after pulling the same file with the same library version.

### Reproduction

Pull the configs using auth0-deploy-cli using v7.12.1

the following file will be created:

prompts/custom-text.json
```
{
  "en": {
    "mfa-otp-enrollment-qr": {
      "buttonText": "Continue (XXXX)",
      "title": "Secure Your Account (S2)",
      "codeEnrollmentText": "Trouble (S2) Scanning?"
    },
    "mfa-phone-enrollment": {
      "smsButtonText": "Text message (XXXX)"
    },
    "mfa-sms-enrollment": {
      "pageTitle": "Secure your account",
      "title": "Secure your account",
      "description": "Enter your mobile number and we'll send you a 6 digit security code.",
      "placeholder": "Enter your mobile number",
      "send-sms-failed": "There was a problem sending the security code. Please try again.",
      "invalid-phone-format": "Mobile number can only include digits.",
      "invalid-phone": "The link has already been used or has expired.",
      "too-many-sms": "There was a problem sending the security code. Please try again.",
      "transaction-not-found": "There was a problem sending the security code. Please try again.",
      "no-phone": "Please enter a mobile number.",
      "logoAltText": "XXXX Logo"
    },
    "mfa-enroll-result": {
      "pageTitle": "Secure your account",
      "enrolledTitle": "Your account is secure",
      "enrolledDescription": "Thanks for verifying your mobile number. We'll redirect you in 3 seconds.",
      "invalidTicketTitle": "This link has expired",
      "invalidTicketDescription": "The link has already been used or has expired",
      "expiredTicketTitle": "This link has expired",
      "expiredTicketDescription": "The link has already been used or has expired",
      "alreadyUsedTitle": "This link has expired",
      "alreadyUsedDescription": "The link has already been used or has expired",
      "alreadyEnrolledDescription": "You've already verified your mobile number.",
      "genericError": "Something went wrong"
    }
  }
}
```

Trying to push the config including this new file with the same cli and version, will result in the following error:

```
Bad Request: Path validation error: 'Invalid value "mfa-enroll-result"' on property prompt (Name of the prompt).
--
  | at fn (/workdir/node_modules/rest-facade/src/Client.js:402:25)
  | at Request.callback (/workdir/node_modules/superagent/src/node/index.js:902:3)
  | at fn (/workdir/node_modules/superagent/src/node/index.js:1129:18)
  | at IncomingMessage.<anonymous> (/workdir/node_modules/superagent/src/node/parsers/json.js:19:7)
  | at Stream.emit (events.js:400:28)
  | at Stream.emit (domain.js:475:12)
  | at Unzip.<anonymous> (/workdir/node_modules/superagent/src/node/unzip.js:54:12)
  | at Unzip.emit (events.js:400:28)
  | at Unzip.emit (domain.js:475:12)
  | at endReadableNT (internal/streams/readable.js:1334:12) {
  | statusCode: 400,
  | requestInfo: {
  | method: 'put',
  | url: 'https://XXXXXXX/api/v2/prompts/mfa-enroll-result/custom-text/en'
  | },
  | originalError: Error: Bad Request
  | at Request.callback (/workdir/node_modules/superagent/src/node/index.js:879:15)
  | at fn (/workdir/node_modules/superagent/src/node/index.js:1129:18)
  | at IncomingMessage.<anonymous> (/workdir/node_modules/superagent/src/node/parsers/json.js:19:7)
  | at Stream.emit (events.js:400:28)
  | at Stream.emit (domain.js:475:12)
  | at Unzip.<anonymous> (/workdir/node_modules/superagent/src/node/unzip.js:54:12)
  | at Unzip.emit (events.js:400:28)
  | at Unzip.emit (domain.js:475:12)
  | at endReadableNT (internal/streams/readable.js:1334:12)
  | at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  | status: 400,
  | response: Response {
  | _events: [Object: null prototype] {},
  | _eventsCount: 0,
  | _maxListeners: undefined,
  | res: [IncomingMessage],
  | request: [Request],
  | req: [ClientRequest],
  | text: `{"statusCode":400,"error":"Bad Request","message":"Path validation error: 'Invalid value \\"mfa-enroll-result\\"' on property prompt (Name of the prompt).","errorCode":"invalid_uri"}`,
  | body: [Object],
  | files: undefined,
  | buffered: true,
  | headers: [Object],
  | header: [Object],
  | statusCode: 400,
  | status: 400,
  | statusType: 4,
  | info: false,
  | ok: false,
  | redirect: false,
  | clientError: true,
  | serverError: false,
  | error: [Error],
  | created: false,
  | accepted: false,
  | noContent: false,
  | badRequest: true,
  | unauthorized: false,
  | notAcceptable: false,
  | forbidden: false,
  | notFound: false,
  | unprocessableEntity: false,
  | type: 'application/json',
  | charset: 'utf-8',
  | links: {},
  | setEncoding: [Function: bound ],
  | redirects: [],
  | pipe: [Function (anonymous)],
  | [Symbol(kCapture)]: false
  | }
  | },
  | type: 'prompts',
  | stage: 'processChanges'
  | }


```

### Environment

Auth0deploy-cli v 7.12.1

We are using private appliance, v [2112](https://auth0.com/releases/2112)

**Comment by locscoutbee** [comment]
Hi @willvedd, I think there are prompts like `mfa-otp` and screen type like `mfa-otp-enrollment-qr` under  prompt. I am not pretty sure but by adding more items in promptScreenTypes may fix the issue. 
![image](https://user-images.githubusercontent.com/90253543/168588930-805070d1-6d0d-4855-9942-9021c40cbbca.png)

**Comment by willvedd** [comment]
Yep, this is definitely an issue with the latest release. I'm now realizing that the logic is more complex and needs to account for all the available screen types grouped under a specific prompt. Will have a fix out for this soon.

**Comment by willvedd** [comment]
[v7.12.2](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.12.2) has corrected the handling of these screen types under the broader prompt groupings by adding a level to establish these screen grouping. Example:

```json
{
  "en": {
    "login": {
      "login": {
        "description": "foo",
        "title": "foo",
        "buttonText": "foo"
      }
    },
    "mfa": {
      "mfa-begin-enroll-options": {
        "title": "foo"
      },
      "mfa-detect-browser-capabilities": {
        "pickAuthenticatorText": "foo"
      },
      "mfa-enroll-result": {
        "genericError": "foo"
      },
      "mfa-login-options": {
        "backText": "foo"
      }
    }
  }
}
```

This better relfects how these prompt groupings are [handled in the API](https://auth0.com/docs/api/management/v2#!/Prompts/put_custom_text_by_language) (also see: [Customize New Universal Login Text Prompts](https://auth0.com/docs/customize/universal-login-pages/customize-login-text-prompts))

After upgrading to 7.12.2, you will need to re-export prompts to be able to perform subsequent imports.

Thanks for the patience on this one!
