### ISSUE TITLE
Getting unauthorized 403 when exporting branding

### ISSUE THREAD

**Issue by kevinmerckx** [auth0/auth0-deploy-cli#651]
I configured the auth0 deploy cli as described in the instructions. When running `a0deploy export --format=directory --output_folder=local --config_file=config.json -d`, I get the following output:

```
2022-09-13T06:13:46.271Z - debug: Start command export
2022-09-13T06:13:47.592Z - info: Loading Auth0 Tenant Data
2022-09-13T06:13:47.751Z - info: Retrieving rules data from Auth0
2022-09-13T06:13:47.886Z - info: Retrieving rulesConfigs data from Auth0
2022-09-13T06:13:48.062Z - info: Retrieving hooks data from Auth0
2022-09-13T06:13:50.367Z - info: Retrieving pages data from Auth0
2022-09-13T06:13:50.533Z - info: Retrieving resourceServers data from Auth0
2022-09-13T06:13:51.696Z - info: Retrieving clients data from Auth0
2022-09-13T06:13:51.849Z - info: Retrieving databases data from Auth0
2022-09-13T06:13:53.004Z - info: Retrieving connections data from Auth0
2022-09-13T06:13:53.144Z - info: Retrieving tenant data from Auth0
2022-09-13T06:13:53.294Z - info: Retrieving emailProvider data from Auth0
2022-09-13T06:13:53.444Z - info: Retrieving clientGrants data from Auth0
2022-09-13T06:13:53.610Z - info: Retrieving guardianFactors data from Auth0
2022-09-13T06:13:53.776Z - info: Retrieving guardianFactorProviders data from Auth0
2022-09-13T06:13:54.947Z - info: Retrieving guardianFactorTemplates data from Auth0
2022-09-13T06:13:56.106Z - info: Retrieving guardianPolicies data from Auth0
2022-09-13T06:13:56.271Z - info: Retrieving guardianPhoneFactorSelectedProvider data from Auth0
2022-09-13T06:13:56.432Z - info: Retrieving guardianPhoneFactorMessageTypes data from Auth0
2022-09-13T06:13:56.591Z - info: Retrieving roles data from Auth0
2022-09-13T06:13:59.883Z - debug: Error calling branding API, The account is not allowed to perform this operation, please contact our support team, status code: 403
2022-09-13T06:13:59.883Z - info: Retrieving branding data from Auth0
2022-09-13T06:14:04.277Z - error: Problem running command export during stage load when processing type prompts
2022-09-13T06:14:04.277Z - error: read ECONNRESET
2022-09-13T06:14:04.278Z - debug: APIError: read ECONNRESET
    at XXXYYYY/.nvm/versions/node/v16.16.0/lib/node_modules/auth0-deploy-cli/node_modules/rest-facade/src/Client.js:402:25
    at Request.callback (XXXYYYY/.nvm/versions/node/v16.16.0/lib/node_modules/auth0-deploy-cli/node_modules/superagent/lib/node/index.js:905:3)
    at ClientRequest.<anonymous> (XXXYYYY/.nvm/versions/node/v16.16.0/lib/node_modules/auth0-deploy-cli/node_modules/superagent/lib/node/index.js:822:12)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
```

Setup:

- **Version of this library used: 7.14.3**
- **Version of the platform or framework used, if applicable: Node 16.16.0**
- **Other relevant versions (language, server software, OS, browser): MacOS 12.5**

**Comment by kevinmerckx** [comment]
@willvedd I'm indeed using the free tiers. After digging a bit more, I found out that what I need to export is not in `branding` but in `pages`. I excluded everything else and it works like a charm. I'm doing that because we use two different tenants, one for development and one for production. The production one is premium, the development one is free tiers.

The weird thing is that I could not find where this is documented. I would expect to see what is possible to access through the CLI for free and premium tiers.

**Comment by thiagocharao** [comment]
Exact same issue here. Not using free tier, in fact we have a Private Cloud instance, although I don't think this is relevant as it looks like an issue with auth0-deploy-cli while retrieving branding data.

Based on Logs it looks like it is getting it too fast?
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1944301/191000318-c484c1df-f07b-49a5-bd29-0436ca30d3c6.png">

**Comment by willvedd** [comment]
Ok I'm pretty sure this is caused because the tenant does not support custom domains, which are required to make branding changes. It's probably sensible to add a check to detect if custom domains are supported and if not, skip the export of branding settings. 

For those who utilize free tiers for their lower-leveled environments, this will obviously impact the ability your replicate prod.

**Comment by thiagocharao** [comment]
In this case we have a custom domain configured for this tenant.

**Comment by thiagocharao** [comment]
Ok so just thought about something, the first screenshot I sent it was complaining about Rate Limit on a /language endpoint.

Then I thought about the Languages I had selected to support (All of them) reduced to the ones I really need to support and voilà, it is working.

![Screenshot 2022-09-21 at 18 12 26](https://user-images.githubusercontent.com/1944301/191569190-5a3a8a08-82de-4bfc-b3ce-3db57a8429ce.png)

It is possibly not related to that particular endpoint for everyone but to the way/speed auth0-deploy-cli is retrieving data from the API.

**Comment by willvedd** [comment]
@thiagocharao What you are mentioning is unrelated to OP's issue. It is expected to hit up against rate limits. Custom text prompts are especially expensive with requests, so it makes sense that reducing the number of supported languages sped up your process. If you still have a problem with the Deploy CLI, please create a new Github issue so we can treat separately.

**Comment by thiagocharao** [comment]
Indeed not the same, I am not getting a 403. Will open a separate issue for this.

**Comment by willvedd** [comment]
Looping back to this and I'm realizing that the debugging message printed by the branding handler is a red herring. If you look at [the relevant code](https://github.com/auth0/auth0-deploy-cli/blob/master/src/tools/auth0/handlers/branding.ts#L63), you will see that this debugging message gets logged but then subsequently handled appropriately. This is confirmed by the `2022-09-13T06:13:59.883Z - info: Retrieving branding data from Auth0` message which actually gets printed _after_ the API request succeeds.

Instead, I'm seeing that prompts is the culprit here. This handler is known to make many concurrent network requests, especially if there are several supported languages. Is it possible that you're running up against limits imposed by the container or hardware? If possible, I'd see if you could increase any imposed limits to allow for the higher number of simultaneous network requests.
