### ISSUE TITLE
a0deploy import failing with error: Object.keys(...).flatMap is not a function

### ISSUE THREAD

**Issue by aayush13890** [auth0/auth0-deploy-cli#685]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello, I have 2 tenants created in my Auth0 subscription. I want to make some configuration changes to one tenant, export this configuration, and then import it in second tenant. I am able to successfully export the configuration from a tenant, but when I am trying to import it in second tenant few of the configurations are getting applied and then the import fails.

### Expectation

The import operation should run successfully.

### Reproduction

**Sample config.json content for export operation:**
{
  "AUTH0_DOMAIN": "dev-xyz.us.auth0.com",
  "AUTH0_CLIENT_ID": "CLIENT_ID",
  "AUTH0_CLIENT_SECRET": "CLIENT_SECRET",
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
      "AUTH0_TENANT_NAME": "dev-xyz",
      "ENV": "DEV"
  },
  "AUTH0_ALLOW_DELETE": false,
  "AUTH0_EXCLUDED_RULES": []
}

**Command used to export the configuration:**
a0deploy export --config_file ./config.json --format yaml --output_folder /root/Auth0/

**Sample config.json for the import operation:**
{
  "AUTH0_DOMAIN": "dev-xyz-import-testing.us.auth0.com",
  "AUTH0_CLIENT_ID": "CLIENT_ID",
  "AUTH0_CLIENT_SECRET": "CLIENT_SECRET",
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
      "AUTH0_TENANT_NAME": "dev-xyz-import-testing",
      "ENV": "DEV"
  },
  "AUTH0_ALLOW_DELETE": false,
  "AUTH0_EXCLUDED_RULES": []
}

**Import command used (I have replaced some sensitive information from the debug messages)**
-bash-4.2# a0deploy import --config_file import_testing/config.json --input_file tenant.yaml --debug true
2022-10-28T00:12:53.849Z - debug: Start command import
2022-10-28T00:12:54.156Z - debug: Loading YAML from /root/Auth0/tenant.yaml
2022-10-28T00:13:09.354Z - info: Getting access token for **CLIENT_ID**/dev-xyz-import-testing.us.auth0.com
2022-10-28T00:13:24.349Z - debug: Start processChanges for rules [delete:0] [update:0], [create:0], [conflicts:0]
2022-10-28T00:13:24.670Z - debug: Start processChanges for hooks [delete:0] [update:0], [create:0], [conflicts:0]
2022-10-28T00:13:25.085Z - debug: Start processChanges for resourceServers [delete:0] [update:0], [create:0], [conflicts:0]
2022-10-28T00:13:25.276Z - debug: Start processChanges for clients [delete:0] [update:3], [create:0], [conflicts:0]
2022-10-28T00:13:25.277Z - debug: Stripping "Auth0 Management API (Aayush)" read-only fields ["jwt_configuration.secret_encoded","client_id"]
2022-10-28T00:13:25.277Z - debug: Stripping "Default App" read-only fields ["jwt_configuration.secret_encoded","client_id"]
2022-10-28T00:13:25.277Z - debug: Stripping "Veritas NBU SaaS" read-only fields ["jwt_configuration.secret_encoded","client_id"]
2022-10-28T00:13:25.483Z - info: Updated [clients]: {"name":"Veritas NBU SaaS","client_id":"**client_id**"}
2022-10-28T00:13:25.484Z - info: Updated [clients]: {"name":"Auth0 Management API (Aayush)","client_id":"Bm8cMeFOAMryOPBrln3ZBUdpddgPhAzf"}
2022-10-28T00:13:25.504Z - info: Updated [clients]: {"name":"Default App","client_id":"**client_id**"}
2022-10-28T00:13:25.731Z - debug: Start processChanges for logStreams [delete:0] [update:0], [create:0], [conflicts:0]
2022-10-28T00:13:25.732Z - info: Updated [attackProtection]: {"brute-force-protection":{"enabled":true},"suspicious-ip-throttling":{"enabled":true}}
2022-10-28T00:13:27.764Z - error: Problem running command import during stage processChanges when processing type prompts
2022-10-28T00:13:27.764Z - error: Object.keys(...).flatMap is not a function
2022-10-28T00:13:27.764Z - debug: TypeError: Object.keys(...).flatMap is not a function
    at PromptsHandler.<anonymous> (/usr/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/prompts.js:223:55)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/prompts.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/prompts.js:4:12)
    at PromptsHandler.updateCustomTextSettings (/usr/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/prompts.js:217:16)
    at PromptsHandler.<anonymous> (/usr/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/prompts.js:211:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/auth0-deploy-cli/lib/tools/auth0/handlers/prompts.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### Deploy CLI version

7.15.1

### Node version

6.14.12

**Comment by willvedd** [comment]
Node v6 is way out of date. Please update to LTS or v11 at the very least.
