### ISSUE TITLE
Auth0 cli dependencies error

### ISSUE THREAD

**Issue by Gentracker1** [auth0/auth0-deploy-cli#874]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,
We are using auth0-cli as a node-module to export the data. We have tried with [7.20.0][7.19.0]....[7.11.0] versions, but same error.

Environment
Node v18.16.0
Using Typescript Version 4.9.5
Using Auth0-cli in AWS Lambda (import { dump } from 'auth0-deploy-cli';)
 "auth0": "^3.2.0",
    "auth0-deploy-cli": "7.11.1"
    
   After npm install
   We are deploying the app to AWS, following error is occurring. 
   ` [ERROR] Could not resolve "superagent-proxy"

    node_modules/rest-facade/src/Client.js:38:12:
      38 │     require('superagent-proxy')(request);
         ╵             ~~~~~~~~~~~~~~~~~~

  You can mark the path "superagent-proxy" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
[auth-cli-error.txt](https://github.com/auth0/auth0-deploy-cli/files/13654040/auth-cli-error.txt)
`

Attaching the full error as well.
   

### Expectation

Able to deploy the lambda with the auth0-cli.

### Reproduction

With node Node v18.16.0
Using Typescript Version 4.9.5
Use the latest [7.20.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.20.0)

Deploy the AWS lambda 
npx cdk deploy <Stack>

### Deploy CLI version

7.20.0

### Node version

v18.16.0

**Comment by m3talsmith** [comment]
@Gentracker1 can you reproduce this locally? Or only on lambda?

If only on lambda, are you using the default image for AWS Node? If not, is it an image we can use to reproduce?

I did write a small test to try it locally and couldn't reproduce the error. I'm trying to get as close to your setup as possible. The lambda environment is my main unknown. I'm happy to dig in more if you could get me that info.

**Comment by Gentracker1** [comment]
![Uploading auth0-720.PNG…]()

**Comment by Gentracker1** [comment]
Updated with the more info and updated the auth0/auth0-cli to the latest version. The error with the latest version is at npm run build.

We are using the WSL Ubuntu with AWS CDK,

**Comment by Gentracker1** [comment]
@m3talsmith I have updated the error desc, we are using the latest auth0-cli. 
Thanks

**Comment by m3talsmith** [comment]
@Gentracker1 I was able to reproduce the `promise-batcher` error. Will have a work around for you soon.

**Comment by m3talsmith** [comment]
@Gentracker1 what happens if you add this to your dependencies:

```
"promise-batcher": "1.0.1"
```

**Comment by Gentracker1** [comment]
Thanks @m3talsmith .
After installing promise-batcher, I was able to build and deploy the lambda.
On executing the lambda, it gives the below error.
`{
  "errorType": "TypeError",
  "errorMessage": "hexoid is not a function",
  "trace": [
    "TypeError: hexoid is not a function",
    "    at node_modules/formidable/src/Formidable.js (/var/task/index.js:68166:20)",
    "    at __require (/var/task/index.js:12:50)",
    "    at node_modules/formidable/src/index.js (/var/task/index.js:69025:22)",
    "    at __require (/var/task/index.js:12:50)",
    "    at node_modules/superagent/lib/node/index.js (/var/task/index.js:73799:22)",
    "    at __require (/var/task/index.js:12:50)",
    "    at node_modules/rest-facade/src/Client.js (/var/task/index.js:116198:19)",
    "    at __require (/var/task/index.js:12:50)",
    "    at node_modules/rest-facade/src/index.js (/var/task/index.js:116454:15)",
    "    at __require (/var/task/index.js:12:50)"
  ]
}`

**Comment by matthewhgentrack** [comment]
Found a similar error for "hexoid" is not a function here: https://github.com/auth0/node-auth0/issues/798
Suggestions for a fix there seem to relate to webpack. Not sure how to resolve for AWS CDK/NodeJsFunction which is bundling via esbuild.

**Comment by matthewhgentrack** [comment]
Overriding the `superagent` version for `rest-facade` in `package.json` seems to workaround the problem.

```
"overrides": {
    "rest-facade": {
      "superagent": "6.0.0"
    }
  }
```
Not an ideal solution to override dependencies though.

**Comment by m3talsmith** [comment]
Tracking down hexoid and superagent errors now @Gentracker1 and @matthewhgentrack

**Comment by m3talsmith** [comment]
This definitely comes down to transitive dependencies of node-auth. Specifically, it comes down to formidable via superagent as @matthewhgentrack points out. A workaround seems to be to downgrade superagent or save the latest formidable to your npm packages.

**Comment by MrOctopus** [comment]
The fix is simple: Don't add add an old promise-batcher version to your direct dependencies. Do an override of the peer dependency itself:
`"overrides": {
    "promise-pool-executor": {
      "promise-batcher": "1.0.2"
    }
  }`
To avoid the hexoid issue, just make sure to use the newest auth0 3.* version (v3.7.2).
